# -*- coding: utf-8 -*-
"""Fraud Transaction Insight (Analisis Data IEEE-CIS Fraud Detection)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjxDinHa_AcJwcgScLCndCrdSTAP-F2C

# **Machine Learning: Advanced Fraud Transaction Detection**
**Feature Engineering & Data Validation**
* Ekstraksi Fitur Velocity (Time-Decay)
* Pemetaan Jaringan Fraud (Bipartite Graph Centrality)
* Time-Based Splitting (Mencegah Data Leakage)
----------------------------------------------------
**Advanced Modelling & Business Evaluation**
* Klasifikasi LightGBM (Native Categorical Handling)
* Evaluasi Metrik Data Imbalanced (PR-AUC)
* Threshold Tuning untuk Optimasi Trade-off Bisnis

>**Aisyah Amalia Hamid @ mal-lia**

# **Dataset IEEE-CIS Fraud Detection (Kaggle Competition)**

### **Setup Environment & Install Libraries**
"""

!pip install -q networkx kaggle

!pip install --upgrade kaggle

"""### **Import Semua Library**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import logging
import networkx as nx
import gc
import os
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("Colab_Fraud")

"""### **Load Dataset**"""

!export KAGGLE_API_TOKEN=KGAT_ef0854da35580bc33289abd43ebe71f1

!mkdir -p ~/.kaggle && echo KGAT_ef0854da35580bc33289abd43ebe71f1 > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token

!kaggle competitions download -c ieee-fraud-detection

!unzip -q ieee-fraud-detection.zip -d /content/data/

# Training Data Paths
TRAIN_TRANS_PATH = '/content/data/train_transaction.csv'
TRAIN_IDENTITY_PATH = '/content/data/train_identity.csv'

# Test Data Paths
TEST_TRANS_PATH = '/content/data/test_transaction.csv'
TEST_IDENTITY_PATH = '/content/data/test_identity.csv'

"""### **Explorary Data Analysis (EDA) Data Testing**"""

df_trans_sample = pd.read_csv(TEST_TRANS_PATH, nrows=10000)
df_id_sample = pd.read_csv(TEST_IDENTITY_PATH, nrows=10000)

print("Info Transaction:")
df_trans_sample.info()

print("5 Baris Pertama Transaction:")
display(df_trans_sample.head())

print("Statistik Deskriptif (Transaction Amount):")
display(df_trans_sample['TransactionAmt'].describe())

print("Info Identity:")
df_id_sample.info()

print("5 Baris Pertama Identity:")
display(df_id_sample.head())

df_test = pd.merge(df_trans_sample, df_id_sample, on='TransactionID', how='left')
print("Info Gabungan Data Test:")
df_test.info()

print("\n5 Baris Pertama Gabungan Data Test:")
display(df_test.head())

missing_data = df_test.isnull().sum()
missing_data = missing_data[missing_data > 0].sort_values(ascending=False)

plt.figure(figsize=(15, 6))
sns.barplot(x=missing_data.index[:30], y=missing_data.values[:30], hue=missing_data.index[:30], palette='viridis', legend=False)
plt.title('Top 30 Kolom dengan Missing Values Terbanyak (Data Test Gabungan)')
plt.xlabel('Kolom')
plt.ylabel('Jumlah Missing Values')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

categorical_cols = ['ProductCD', 'card4', 'card6', 'P_emaildomain', 'R_emaildomain', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9']

plt.figure(figsize=(20, 15))
for i, col in enumerate(categorical_cols):
    if col in df_test.columns:
        plt.subplot(4, 4, i + 1)
        sns.countplot(y=df_test[col], order=df_test[col].value_counts().index, hue=df_test[col], palette='crest', legend=False)
        plt.title(f'Distribusi {col}')
        plt.tight_layout()
plt.show()

numerical_cols_to_plot = ['TransactionAmt', 'TransactionDT', 'dist1', 'D1', 'D2', 'D3', 'C1', 'C2', 'C3']

plt.figure(figsize=(20, 15))
for i, col in enumerate(numerical_cols_to_plot):
    if col in df_test.columns:
        plt.subplot(3, 3, i + 1)
        sns.histplot(df_test[col].dropna(), bins=50, kde=True, color='darkgreen')
        plt.title(f'Distribusi {col}')
        plt.xlabel(col)
        plt.ylabel('Frekuensi')
        plt.tight_layout()
plt.show()

"""### **Exploratory Data Analysis (EDA) Data Training**"""

df_train_trans = pd.read_csv(TRAIN_TRANS_PATH, nrows=10000)
df_train_id = pd.read_csv(TRAIN_IDENTITY_PATH, nrows=10000)

print("Info Transaction Training:")
df_train_trans.info()

print("5 Baris Pertama Transaction Training:")
display(df_train_trans.head())

print("Info Identity Training:")
df_train_id.info()

print("5 Baris Pertama Identity Training:")
display(df_train_id.head())

df_train = pd.merge(df_train_trans, df_train_id, on='TransactionID', how='left')
print("Info Gabungan Data Training:")
df_train.info()

print("\n5 Baris Pertama Gabungan Data Training:")
display(df_train.head())

print("Cek Imbalance Target (isFraud):")
fraud_ratio = df_train['isFraud'].mean() * 100
print(f"Persentase Fraud dalam sample training: {fraud_ratio:.4f}% (Sangat Imbalanced!)")

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
sns.histplot(df_train[df_train['isFraud']==0]['TransactionAmt'], bins=50, label='Normal', color='darkred', ax=axes[0], kde=True)
sns.histplot(df_train[df_train['isFraud']==1]['TransactionAmt'], bins=50, label='Fraud', color='pink', ax=axes[0], kde=True)
axes[0].set_title('Distribusi Nilai Transaksi (Normal vs Fraud)')
axes[0].legend()
sns.countplot(x='isFraud', data=df_train, ax=axes[1], hue='isFraud', palette=['pink', 'darkred'], legend=False)
axes[1].set_title('Jumlah Label isFraud (Imbalance Terlihat)')
plt.tight_layout()
plt.show()

missing_data_train = df_train.isnull().sum()
missing_data_train = missing_data_train[missing_data_train > 0].sort_values(ascending=False)

plt.figure(figsize=(15, 6))
sns.barplot(x=missing_data_train.index[:30], y=missing_data_train.values[:30], hue=missing_data_train.index[:30], palette='Reds_d', legend=False)
plt.title('Top 30 Kolom dengan Missing Values Terbanyak (Data Training Gabungan)')
plt.xlabel('Kolom')
plt.ylabel('Jumlah Missing Values')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

categorical_cols_train = ['ProductCD', 'card4', 'card6', 'P_emaildomain', 'R_emaildomain', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9']

plt.figure(figsize=(20, 18))
for i, col in enumerate(categorical_cols_train):
    if col in df_train.columns:
        plt.subplot(4, 4, i + 1)
        sns.countplot(y=df_train[col], order=df_train[col].value_counts().index, hue=df_train[col], palette='Reds_d', legend=False)
        plt.title(f'Distribusi {col}')
        plt.tight_layout()
plt.show()

numerical_cols_to_plot_train = ['TransactionAmt', 'TransactionDT', 'dist1', 'D1', 'D2', 'D3', 'C1', 'C2', 'C3']

plt.figure(figsize=(20, 15))
for i, col in enumerate(numerical_cols_to_plot_train):
    if col in df_train.columns:
        plt.subplot(3, 3, i + 1)
        sns.histplot(df_train[col].dropna(), bins=50, kde=True, color='darkred')
        plt.title(f'Distribusi {col}')
        plt.xlabel(col)
        plt.ylabel('Frekuensi')
        plt.tight_layout()
plt.show()

"""## **IEEE Fraud Pipeline untuk Data Training**"""

class IEEEFraudPipeline:
    def __init__(self, transaction_path: str, identity_path: str):
        self.transaction_path = transaction_path
        self.identity_path = identity_path
        self.df = pd.DataFrame()

    def reduce_mem_usage(self, df: pd.DataFrame) -> pd.DataFrame:
        start_mem = df.memory_usage().sum() / 1024**2
        logger.info(f'💾 Memory awal: {start_mem:.2f} MB')

        for col in df.columns:
            col_type = df[col].dtype
            if col_type != object:
                c_min = df[col].min()
                c_max = df[col].max()
                if str(col_type)[:3] == 'int':
                    if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                        df[col] = df[col].astype(np.int8)
                    elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                        df[col] = df[col].astype(np.int16)
                    elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                        df[col] = df[col].astype(np.int32)
                    elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                        df[col] = df[col].astype(np.int64)
                else:
                    if col == 'TransactionAmt':
                        df[col] = df[col].astype(np.float32) # Ensure at least float32
                    elif c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                        df[col] = df[col].astype(np.float16)
                    elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                        df[col] = df[col].astype(np.float32)

        end_mem = df.memory_usage().sum() / 1024**2
        logger.info(f'💾 Memory akhir: {end_mem:.2f} MB (Turun {(start_mem - end_mem)/start_mem*100:.1f}%)')
        return df

    def load_and_merge(self) -> None:
        logger.info("📂 Memuat & Menggabungkan Transaction dan Identity...")
        df_trans = pd.read_csv(self.transaction_path)
        df_id = pd.read_csv(self.identity_path)
        self.df = df_trans.merge(df_id, on='TransactionID', how='left')
        if 'isFraud' in df_trans.columns:
            self.df['isFraud'] = df_trans['isFraud']
        del df_trans, df_id
        gc.collect()
        self.df = self.reduce_mem_usage(self.df)

    def extract_time_features(self) -> None:
        logger.info("⏳ Ekstraksi fitur waktu (Hour & Day)...")
        self.df['Transaction_Hour'] = np.floor((self.df['TransactionDT'] / 3600) % 24)
        self.df['Transaction_Day'] = np.floor((self.df['TransactionDT'] / (3600 * 24) - 1) % 7)

    def generate_velocity_features(self) -> None:
        logger.info("🚀 Membangun Velocity Features (Kecepatan transaksi per kartu)...")
        if 'card1' in self.df.columns and self.df['card1'].dtype == 'object':
            self.df['card1'] = pd.to_numeric(self.df['card1'], errors='coerce')
        self.df = self.df.sort_values(by=['card1', 'TransactionDT'])
        self.df['time_since_last_txn_card'] = self.df.groupby('card1')['TransactionDT'].diff().fillna(-1)
        self.df['card1_daily_count'] = self.df.groupby(['card1', 'Transaction_Day'])['TransactionID'].transform('count')

    def generate_network_features(self) -> None:
        logger.info("🕸️ Membangun Network Features (Bipartite Graph Kartu-Device)...")
        df_graph = self.df.dropna(subset=['DeviceInfo', 'card1']).copy()
        df_graph['card1'] = df_graph['card1'].astype(str)

        if not df_graph.empty:
            G = nx.from_pandas_edgelist(df_graph, source='card1', target='DeviceInfo')
            centrality = nx.degree_centrality(G)

            self.df['card1_degree'] = self.df['card1'].astype(str).map(centrality).fillna(0)
            self.df['DeviceInfo_degree'] = self.df['DeviceInfo'].map(centrality).fillna(0)
        else:
            self.df['card1_degree'] = 0
            self.df['DeviceInfo_degree'] = 0

    def run_pipeline(self) -> pd.DataFrame:
        self.load_and_merge()
        self.extract_time_features()
        self.generate_velocity_features()
        self.generate_network_features()
        logger.info(f"✅ Pipeline selesai! Data akhir berukuran: {self.df.shape}")
        return self.df

train_pipeline = IEEEFraudPipeline(TRAIN_TRANS_PATH, TRAIN_IDENTITY_PATH)
df_train_processed = train_pipeline.run_pipeline()

print("Info Data Training Setelah Pipeline:")
df_train_processed.info()

print("\n5 Baris Pertama Data Training Setelah Pipeline:")
display(df_train_processed.head())

"""### **Visualisasi Data Training**"""

fig, axes = plt.subplots(1, 2, figsize=(15, 5))
hourly_fraud = df_train_processed.groupby('Transaction_Hour')['isFraud'].mean()
sns.barplot(x=hourly_fraud.index, y=hourly_fraud.values, ax=axes[0], palette='Reds', hue=hourly_fraud.index, legend=False)
axes[0].set_title('Fraud Rate per Jam Transaksi')
axes[0].set_xlabel('Jam (0-23)')
axes[0].set_ylabel('Persentase Fraud')
sns.boxplot(x='isFraud', y='card1_degree', data=df_train_processed, ax=axes[1], palette='Reds', hue='isFraud', legend=False)
axes[1].set_title('Network Degree (Centrality) vs Fraud')
axes[1].set_xticks([0, 1]) # Explicitly set x-ticks
axes[1].set_xticklabels(['Normal', 'Fraud'])
axes[1].set_ylabel('Degree Centrality (Semakin tinggi = makin terhubung)')

plt.tight_layout()
plt.show()

print("Heatmap Korelasi dengan Target (isFraud):")
top_features = ['TransactionAmt', 'Transaction_Hour', 'card1_daily_count', 'time_since_last_txn_card',
                'card1_degree', 'DeviceInfo_degree', 'isFraud']
orr = df_train_processed[top_features].corr()
fig = plt.figure(figsize=(10, 8))
sns.heatmap(orr, annot=True, cmap='Reds', fmt='.2f')
plt.title('Korelasi Fitur-Fitur Utama terhadap Fraud')
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(18, 12))
axes = axes.flatten()
categorical_features = ['ProductCD', 'card4', 'card6', 'DeviceType']

for i, feature in enumerate(categorical_features):
    if feature in df_train_processed.columns:
        fraud_rate = df_train_processed.groupby(feature)['isFraud'].mean().sort_values(ascending=False)
        sns.barplot(x=fraud_rate.index, y=fraud_rate.values, ax=axes[i], palette='magma', hue=fraud_rate.index, legend=False)
        axes[i].set_title(f'Fraud Rate per {feature}')
        axes[i].set_xlabel(feature)
        axes[i].set_ylabel('Fraud Rate')
        axes[i].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""### **Modelling [Baseline] untuk Validasi Training Dataset**"""

!pip install -q lightgbm

import lightgbm as lgb
from sklearn.metrics import average_precision_score, precision_recall_curve, roc_auc_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

logger.info("Mempersiapkan fitur kategorikal dan numerikal...")

for col in df_train_processed.columns:
    if df_train_processed[col].dtype == 'object':
        df_train_processed[col] = df_train_processed[col].astype('category')

drop_cols = ['TransactionID', 'TransactionDT', 'isFraud']
feature_cols = [col for col in df_train_processed.columns if col not in drop_cols]

logger.info(f"Total fitur yang digunakan: {len(feature_cols)} fitur (Termasuk Kategorikal!)")
logger.info("Melakukan Time-Based Splitting (Mencegah kebocoran masa depan)...")
df_train_processed = df_train_processed.sort_values('TransactionDT').reset_index(drop=True)

X = df_train_processed[feature_cols]
y = df_train_processed['isFraud']
split_index = int(len(X) * 0.7)
X_train, X_test = X.iloc[:split_index], X.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

logger.info(f"Ukuran Data Train: {X_train.shape}, Data Test: {X_test.shape}")

logger.info("Melatih model LightGBM...")
model = lgb.LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)
y_proba = model.predict_proba(X_test)[:, 1]
y_pred_default = (y_proba >= 0.5).astype(int)
y_pred_custom  = (y_proba >= 0.7).astype(int)

print("REPORT: THRESHOLD DEFAULT (0.5) - Agresif Menangkap Fraud")
print(classification_report(y_test, y_pred_default))

print("\nREPORT: THRESHOLD CUSTOM (0.7) - Fokus Mengurangi Salah Blokir")
print(classification_report(y_test, y_pred_custom))

pr_auc = average_precision_score(y_test, y_proba)
print(f"PR-AUC Score Akhir: {pr_auc:.4f}")

precision, recall, thresholds = precision_recall_curve(y_test, y_proba)

plt.figure(figsize=(10, 6))
plt.plot(thresholds, precision[:-1], 'b--', label='Precision (Seberapa akurat tebakan fraud kita?)', lw=2)
plt.plot(thresholds, recall[:-1], 'r-', label='Recall (Berapa banyak total fraud yg ditangkap?)', lw=2)
plt.axvline(x=0.7, color='green', linestyle=':', label='Threshold Pilihan Tim Bisnis (0.7)')
plt.xlabel('Threshold Probabilitas')
plt.ylabel('Skor Metrik')
plt.title('Threshold Tuning: Menyeimbangkan Pencegahan Fraud dan Pengalaman Pelanggan')
plt.legend(loc='lower left')
plt.grid(True)
plt.show()

importance = pd.Series(model.feature_importances_, index=feature_cols).sort_values(ascending=False)
plt.figure(figsize=(10, 8))
sns.barplot(x=importance.values[:15], y=importance.index[:15], color='firebrick')
plt.title('Top 15 Feature Importance (Sekarang ada Kategorikal!)')
plt.xlabel('LightGBM Split/Gain')
plt.tight_layout()
plt.show()

